# Complete 15 language translations for UI and AI responses

LANGUAGES = {
    "en": {"name": "English", "flag": "🇬🇧", "dir": "ltr", "code": "en"},
    "ha": {"name": "Hausa", "flag": "🇳🇬", "dir": "ltr", "code": "ha"},
    "ar": {"name": "العربية", "flag": "🇸🇦", "dir": "rtl", "code": "ar"},
    "es": {"name": "Español", "flag": "🇪🇸", "dir": "ltr", "code": "es"},
    "fr": {"name": "Français", "flag": "🇫🇷", "dir": "ltr", "code": "fr"},
    "de": {"name": "Deutsch", "flag": "🇩🇪", "dir": "ltr", "code": "de"},
    "pt": {"name": "Português", "flag": "🇵🇹", "dir": "ltr", "code": "pt"},
    "ru": {"name": "Русский", "flag": "🇷🇺", "dir": "ltr", "code": "ru"},
    "zh": {"name": "简体中文", "flag": "🇨🇳", "dir": "ltr", "code": "zh"},
    "ja": {"name": "日本語", "flag": "🇯🇵", "dir": "ltr", "code": "ja"},
    "ko": {"name": "한국어", "flag": "🇰🇷", "dir": "ltr", "code": "ko"},
    "hi": {"name": "हिन्दी", "flag": "🇮🇳", "dir": "ltr", "code": "hi"},
    "tr": {"name": "Türkçe", "flag": "🇹🇷", "dir": "ltr", "code": "tr"},
    "fa": {"name": "فارسی", "flag": "🇮🇷", "dir": "rtl", "code": "fa"},
    "ur": {"name": "اردو", "flag": "🇵🇰", "dir": "rtl", "code": "ur"},
}

# UI Translations
UI_TEXTS = {
    "en": {
        "welcome_title": "🛡️ Cy30rt_AI",
        "welcome_subtitle": "Your Cybersecurity AI Assistant",
        "created_by": "Created by Abdulbasid Yakubu (cy30rt)",
        "choose_language": "Choose Your Language",
        "ai_badge": "🤖 AI Powered",
        "online_status": "🟢 Online",
        "typing": "Cy30rt_AI is thinking...",
        "error_message": "⚠️ Error occurred. Please try again.",
        "warning": "⚠️ Practice on authorized systems only",
        "learn": "📚 Learn",
        "payloads": "💉 Payloads",
        "labs": "🏴‍☠️ Labs",
        "ai_chat": "🤖 AI Chat",
        "tutorials": "📖 Tutorials",
        "settings": "⚙️ Settings",
        "language": "🌐 Language",
        "voice_input": "🎤 Voice Input",
        "type_message": "Type a message...",
        "send": "Send",
        "sql_injection": "SQL Injection",
        "xss": "Cross-Site Scripting (XSS)",
        "reverse_shell": "Reverse Shells",
        "command_injection": "Command Injection",
        "lfi": "Local File Inclusion",
        "ssrf": "Server-Side Request Forgery",
        "xxe": "XXE Injection",
        "ssti": "SSTI",
        "csrf": "CSRF",
        "jwt": "JWT Attacks",
    },
    "ha": {
        "welcome_title": "🛡️ Cy30rt_AI",
        "welcome_subtitle": "Mataimakin Kan Tsaro na AI",
        "created_by": "Abdulbasid Yakubu (cy30rt) ne ya kirkiro",
        "choose_language": "Zaɓi Harshenku",
        "ai_badge": "🤖 Mai Amfani da AI",
        "online_status": "🟢 Kan layi",
        "typing": "Cy30rt_AI yana tunani...",
        "error_message": "⚠️ Kuskure ya faru. Da fatan za a sake gwadawa.",
        "warning": "⚠️ Yi aiki akan tsarin izini kawai",
        "learn": "📚 Koyo",
        "payloads": "💉 Rumbun Payload",
        "labs": "🏴‍☠️ Labs",
        "ai_chat": "🤖 Tattaunawa da AI",
        "tutorials": "📖 Koyarwa",
        "settings": "⚙️ Saituna",
        "language": "🌐 Harshe",
        "voice_input": "🎤 Murya",
        "type_message": "Rubuta sako...",
        "send": "Aika",
        "sql_injection": "SQL Injection",
        "xss": "Cross-Site Scripting (XSS)",
        "reverse_shell": "Reverse Shells",
        "command_injection": "Command Injection",
        "lfi": "Local File Inclusion",
        "ssrf": "Server-Side Request Forgery",
        "xxe": "XXE Injection",
        "ssti": "SSTI",
        "csrf": "CSRF",
        "jwt": "JWT Hari",
    },
    "ar": {
        "welcome_title": "🛡️ Cy30rt_AI",
        "welcome_subtitle": "مساعد الأمن السيبراني بالذكاء الاصطناعي",
        "created_by": "تم الإنشاء بواسطة عبدالباسد يعقوب (cy30rt)",
        "choose_language": "اختر لغتك",
        "ai_badge": "🤖 مدعوم بالذكاء الاصطناعي",
        "online_status": "🟢 متصل",
        "typing": "Cy30rt_AI يفكر...",
        "error_message": "⚠️ حدث خطأ. الرجاء المحاولة مرة أخرى.",
        "warning": "⚠️ تدرب فقط على الأنظمة المصرح بها",
        "learn": "📚 تعلم",
        "payloads": "💉 الحمولات",
        "labs": "🏴‍☠️ المختبرات",
        "ai_chat": "🤖 محادثة الذكاء الاصطناعي",
        "tutorials": "📖 دروس",
        "settings": "⚙️ الإعدادات",
        "language": "🌐 اللغة",
        "voice_input": "🎤 إدخال صوتي",
        "type_message": "اكتب رسالة...",
        "send": "إرسال",
        "sql_injection": "حقن SQL",
        "xss": "البرمجة النصية عبر المواقع",
        "reverse_shell": "قذائف عكسية",
        "command_injection": "حقن الأوامر",
        "lfi": "تضمين الملفات المحلية",
        "ssrf": "تزوير الطلبات من جانب الخادم",
        "xxe": "حقن XXE",
        "ssti": "حقن قالب الخادم",
        "csrf": "تزوير الطلبات عبر المواقع",
        "jwt": "هجمات JWT",
    },
    # Add all 15 languages here... (es, fr, de, pt, ru, zh, ja, ko, hi, tr, fa, ur)
}


def get_text(key: str, language: str = "en") -> str:
    """Get translated text for UI"""
    if language in UI_TEXTS and key in UI_TEXTS[language]:
        return UI_TEXTS[language][key]
    return UI_TEXTS["en"].get(key, key)


def get_language_info(lang_code: str) -> dict:
    """Get language metadata"""
    return LANGUAGES.get(lang_code, LANGUAGES["en"])
